// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using doanC_Admin.Models;

#nullable disable

namespace doanC_Admin.Migrations
{
    [DbContext(typeof(FoodStreetGuideDBContext))]
    partial class FoodStreetGuideDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("doanC_Admin.Models.AdminUser", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AdminId");

                    b.ToTable("AdminUsers");
                });

            modelBuilder.Entity("doanC_Admin.Models.AudioFile", b =>
                {
                    b.Property<int>("AudioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AudioId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("PointId")
                        .HasColumnType("int");

                    b.HasKey("AudioId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PointId");

                    b.ToTable("AudioFiles");
                });

            modelBuilder.Entity("doanC_Admin.Models.GeoFenceLog", b =>
                {
                    b.Property<int>("GeoLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeoLogId"));

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EnterTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExitTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PointId")
                        .HasColumnType("int");

                    b.HasKey("GeoLogId");

                    b.ToTable("GeoFenceLogs");
                });

            modelBuilder.Entity("doanC_Admin.Models.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageId"));

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("doanC_Admin.Models.LocationPoint", b =>
                {
                    b.Property<int>("PointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PointId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PointId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Address");

                    b.Property<string>("AudioFile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AudioFile");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Category");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("CreatedBy");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Image");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Language");

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("Latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("Longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Name");

                    b.Property<string>("OpeningHours")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OpeningHours");

                    b.Property<string>("PriceRange")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PriceRange");

                    b.Property<double?>("Radius")
                        .HasColumnType("float")
                        .HasColumnName("Radius");

                    b.Property<double?>("Rating")
                        .HasColumnType("float")
                        .HasColumnName("Rating");

                    b.Property<int?>("ReviewCount")
                        .HasColumnType("int")
                        .HasColumnName("ReviewCount");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("UpdatedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("PointId");

                    b.HasIndex("CreatedBy");

                    b.ToTable("LocationPoints", (string)null);
                });

            modelBuilder.Entity("doanC_Admin.Models.QRCode", b =>
                {
                    b.Property<int>("QrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("QrId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QrId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("PointId")
                        .HasColumnType("int")
                        .HasColumnName("PointId");

                    b.Property<string>("QrContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QrContent");

                    b.Property<string>("QrImagePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("QrImagePath");

                    b.HasKey("QrId");

                    b.HasIndex("PointId");

                    b.ToTable("QRCodes", (string)null);
                });

            modelBuilder.Entity("doanC_Admin.Models.QRScanLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("DeviceId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int>("PointId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScanTime")
                        .HasColumnType("datetime2");

                    b.HasKey("LogId");

                    b.HasIndex("PointId");

                    b.ToTable("QRScanLogs");
                });

            modelBuilder.Entity("doanC_Admin.Models.TTSLog", b =>
                {
                    b.Property<int>("TtsLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TtsLogId"));

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PlayedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PointId")
                        .HasColumnType("int");

                    b.HasKey("TtsLogId");

                    b.ToTable("TTSLogs");
                });

            modelBuilder.Entity("doanC_Admin.Models.AudioFile", b =>
                {
                    b.HasOne("doanC_Admin.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("doanC_Admin.Models.LocationPoint", "LocationPoint")
                        .WithMany()
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("LocationPoint");
                });

            modelBuilder.Entity("doanC_Admin.Models.LocationPoint", b =>
                {
                    b.HasOne("doanC_Admin.Models.AdminUser", "Admin")
                        .WithMany()
                        .HasForeignKey("CreatedBy");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("doanC_Admin.Models.QRCode", b =>
                {
                    b.HasOne("doanC_Admin.Models.LocationPoint", "LocationPoint")
                        .WithMany()
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocationPoint");
                });

            modelBuilder.Entity("doanC_Admin.Models.QRScanLog", b =>
                {
                    b.HasOne("doanC_Admin.Models.LocationPoint", "LocationPoint")
                        .WithMany()
                        .HasForeignKey("PointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocationPoint");
                });
#pragma warning restore 612, 618
        }
    }
}
